### ISSUE TITLE
query：Post frontmatter 的tag字段似乎在文章及站点中没有体现

### ISSUE THREAD

**Issue by lateautumn2** [huaixuOvO/prologue.dev#25]
如题，文章中的tag字段似乎没有什么用处，没有一个tag页承载

**Comment by huaixuOvO** [comment]
非常感谢您的反馈（GitHub上第一个Issue），是我之前添加到contentlayer本来以后想调用的，现在解决了，为了避免重复个人博客pr带来的不便，我做了个[Prologue-Blog-Template](https://github.com/huaixuOvO/Prologue-Blog-Template)，只需要修改`/data`内的内容就能迁移，当然也可能会有细节上的不足。

![image](https://github.com/huaixuOvO/prologue.dev/assets/107928988/0a8a397c-1e6b-4a57-8fad-33087416d12a)



搜索引擎和标签云在/Blog页面，也实现通过tag找相关posts，tags可以是包含多个的。

![image](https://github.com/huaixuOvO/prologue.dev/assets/107928988/0e90d5d0-65c7-4cba-971f-7729c2fb87a8)

template demo: [https://prologue-blog-template.vercel.app/](https://prologue-blog-template.vercel.app/)

（我几乎没有技术，若有问题，请见谅）

**Comment by lateautumn2** [comment]
感谢添加，在v2上看到你的留言，我很喜欢这个风格，但是next.js于我而言是完全不会，只能麻烦你添加了
